name: "Release Pipeline Labeler"
on:
  issues:
     types: [closed]
  schedule:
    - cron: 20 14 * * * # 4:20pm Zurich

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: v18
          path: ./actions
      - name: Checkout Repo
        if: github.event_name != 'issues'
        uses: actions/checkout@v2
        with:
          path: ./repo
          fetch-depth: 0
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: "Run Release Pipeline Labeler"
        uses: ./actions/release-pipeline
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          notYetReleasedLabel: unreleased
          insidersReleasedLabel: insiders-released
